# Generated by Django 4.2.5 on 2023-09-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seccion',
        ),
    ]
